### ISSUE TITLE
trouble downloading study_monitoring_sites.zip with sbtools

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-gw-hw-model-prep#10]
Issue downloading study_monitoring_sites.zip from https://www.sciencebase.gov/catalog/item/623e54c4d34e915b67d83580
```
sbtools::item_file_download(sb_id = "623e54c4d34e915b67d83580", names = "study_monitoring_sites.zip", destinations = "1_fetch/in", overwrite_file = TRUE)
Error in sbtools::item_file_download(sb_id = "623e54c4d34e915b67d83580",  : 
  623e54c4d34e915b67d83580Item does not contain all requested files
```
Likely due to the display of the study_monitoring_sites files being unzipped in the release. Note that no errors occur when using sciencebasepy

Need to find work around for this pipeline to successfully run [1_fetch.R#L41-L49](https://github.com/USGS-R/drb-gw-hw-model-prep/blob/d4198cf172296f12018bc30f4639e1a9ece4cadc/1_fetch.R#L41-L49) and build target `p1_drb_temp_sites_shp`

**Comment by lekoenig** [comment]
Closing this issue as addressed in #11
