### ISSUE TITLE
Investigate NA in raster extraction for depth to bedrock

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-gw-hw-model-prep#13]
Following GW-HW check-in discussion (07/19), noting 2 observations related to NAs in the processing step for depth to bedrock raster: 

#### 1. Complete rasters not always entirely encapsulated within polygon boundary of given reach catchment/buffer.
Example with 100 m buffer: 
<img src="https://user-images.githubusercontent.com/36547359/180067165-638e84d4-bf3b-41bc-a7cd-c84212bf0e2f.png" width="300">

Further exploration shows that this improves with a  larger buffer (500m) - _note NA is black in this image_
<img src="https://user-images.githubusercontent.com/36547359/180067521-7d02770f-7d87-4626-9877-8f8aca60f31b.png" width="300">

**To do:** Determine the threshold for counting raster within AOI defined by polygon boundary, if it exists.
**Decision:** For our pipeline, using 250m buffer seems most appropriate given the res of spatial dataset 

#### 2. Some NA's appearing through summarization of raster per polygon.

*  When `na.rm == FALSE`, in red are the catchments (top) & buffered_500m reahces (bottom) with NA summarization result for raster value aggregation (width of buffer doesn't change the identified catchments/reaches). So far, they do not appear linked to actually NA raster values.  

<img src="https://user-images.githubusercontent.com/36547359/180065708-b2f2a2bb-0b20-4573-8123-e6ccb77ed6b9.png" width="300">
<img src="https://user-images.githubusercontent.com/36547359/180064493-f349fe85-ef0b-4011-9176-49fe523b5337.png" width="300">

*  When `na.rm == TRUE`, these pixels get a summarization output value other than NA. 
   * See below buffered reaches (500m) when `na.rm== T` NA polygons in red are expected here as there is no data on delta.
<img src="https://user-images.githubusercontent.com/36547359/180063112-cc84d690-a0d9-41fc-9a08-7f74d6424bbe.png" width="300">

**To do:** Determine why certain catchments get aggregated to NA
**Decision:** Issue more/less resolves itself when `na.rm = TRUE`, so setting that in pipeline but documenting here for further discussion.

For further exploration, reproducible gist [here](https://gist.github.com/msleckman/2bbe4730d55153c6c5bc767853052465)

**Comment by lekoenig** [comment]
@msleckman, was this issue addressed in #18?
