### ISSUE TITLE
Add all catchments per reach target to pipeline

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-gw-hw-model-prep#15]
Produce a sf dataframe that links each reach to all catchments that drain to that reach 

Inputs: 
* NHD catchments: either form NHD catchment gkpg from [drb-network-prep](https://github.com/USGS-R/drb-network-prep/tree/main/1_fetch/out) or pulling directly with `get_nhdplys(comid = p1_nhd_reaches$comid, realization = 'catchment')`
* `p1_drb_comids_all_tribs` 

Process: join two inputs using featureid and comid linkage and disolve such that each reach is tied to single catchment polygon 

Use for the depth to bedrock processing and any other raster processing that requires raster value summarization within such catchment area.

**Comment by lekoenig** [comment]
@msleckman Sorry I missed your ping from before. I agree that this issue is addressed in #18.
