### ISSUE TITLE
reach without catchment

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb-gw-hw-model-prep#20]
Reach `COMID: 4188275` (len = 48 m) does not have an associated catchment from nhdplustools

![image](https://user-images.githubusercontent.com/36547359/182889970-da9f1c18-9835-4815-ab37-a59ac6172016.png)

_Zoom out:_

![image](https://user-images.githubusercontent.com/36547359/182890812-b8ad3aae-24ef-4ccf-9216-028820e76e46.png)

Should we remove this reach? For task in #18 assuming we are going the route of capturing depth to bedrock within the reach's buffer area, the buffering of this reach works and ensures we have a encircling polygon tied to this reach. But down the line, we may run into issues with this reach.

**Comment by lekoenig** [comment]
I think there are somewhere around 50 reaches in `p1_nhd_reaches_along_NHM` that have `AREASQKM == 0` and do not have associated catchments. For these reaches without catchments, we won't have climate data referenced to them and we won't be able to process raster data at the catchment-scale. 

@msleckman and @janetrbarclay, can you think of any applications or scenarios where we'd want to retain these reaches in our model prep repo? They are generally small artificial paths or connectors and so are important to retain for network navigation, but may end up getting omitting either way when we compile reach or catchment-scale features. 

We currently pull the "full" crosswalk table that includes divergent reaches and these zero-area reaches. However, we could pull the version of the crosswalk table that omits zero-area reaches instead (in drb-network-prep [here](https://github.com/USGS-R/drb-network-prep/blob/main/2_process.R#L34)). I came across this same problem in my open met data PR and created a new target called `p2_nhd_reaches_along_NHM_w_cats` (in [this](https://github.com/USGS-R/drb-gw-hw-model-prep/pull/19/commits/a119f58ee86b310c8f5fa2b404dbc898c2e385de) commit), but maybe it'd be more straightforward to use the alternative crosswalk table if we'll always want to omit the zero-area reaches when prepping model inputs.
