### ISSUE TITLE
Create feather file that includes gw-relevant attributes and modflow values

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-gw-hw-model-prep#21]
River-dl is expecting a feather file that contains all the catchment attributes. We will need to combine the groundwater-relevant features with the MODFLOW outputs that Janet has compiled.

**Comment by lekoenig** [comment]
The MODFLOW values on caldera are in these files: 

- `MODFLOW_params_NHM_zell2020_wrr_02.feather`
- `MODFLOW_Discharge_NHM_zell2020_wrr_02.feather`

**Comment by janetrbarclay** [comment]
Here are the paths for the data extracted from modflow.

Simulated gw discharge:
/caldera/projects/usgs/water/impd/pump/drb-gw-hw-temp/data_modflow/data_zell2020_wrr/MODFLOW_Discharge_NHM_zell2020_wrr_02.feather

Calibrated ksat: 
/caldera/projects/usgs/water/impd/pump/drb-gw-hw-temp/data_modflow/data_zell2020_wrr/MODFLOW_params_NHM_zell2020_wrr_02.feather
