### ISSUE TITLE
Adjust pipeline phase names to reflect different sets of experiments?

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-gw-hw-model-prep#23]
Currently our pipeline uses the ~default phase structure of `1_fetch` and `2_process`. However, it might help us keep the targets straight if we renamed the process phase to align with our two sets of model experiments, i.e. `2_process` becomes `2_nhd_downscaling` and `3_nhm_groundwater`.

**Comment by janetrbarclay** [comment]
I don't have strong thoughts, but that seems reasonable to me.
