### ISSUE TITLE
Resolve remaining issues running adjusted NHM widths

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-gw-hw-model-prep#33]
On second look, there appear to be some errors with running the adjusted NHM widths from #30 through river-dl.

_From @janetrbarclay:_

- [x]  We need to change "segidnat" to "seg_id_nat" in the column names
- [x] Also, seg_id_nat should be numeric (either int or float is fine)
- [x] 3 segments (1437, 1442, and 1485) have duplicate entries in the attribute feather file with different widths
- [x] 1 segment (1721) is missing an entry
- [x] [there 1 extra segment (3558) but this isn't a problem]

**Comment by lekoenig** [comment]
> [there 1 extra segment (3558) but this isn't a problem]

seg_id_nat 3558 is a little reach that drains into a tributary of the mainstem Delaware River (colored in red below). Janet mentioned that at least in the earlier PRMS-SNTemp data, that reach had either really high or really low temps, so Janet/Simon opted to exclude it. We'll leave this reach in the NHM/widths feather file for now since 1) we're not sure if the newer SNTemp data look more reasonable and 2) because leaving the reach in doesn't throw any errors when running river-dl.

![3558](https://user-images.githubusercontent.com/8785034/188994869-8296175a-996e-4b3a-be6b-e65d504ed26e.png)

**Comment by janetrbarclay** [comment]
Following up on this, the temps (and maybe other data) for reach 3558 are weird in the newer sntemp outputs as well
![image](https://user-images.githubusercontent.com/3833808/189191666-aa9b4200-5e7b-40e5-9b91-4ac8c6d7dcec.png)
