### ISSUE TITLE
Add data related to segment canopy cover/shade?

### ISSUE THREAD

**Issue by lekoenig** [USGS-R/drb-gw-hw-model-prep#6]
_From Janet:_

> [Shade could be a] factor that might mediate the influence of atmospheric conditions vs groundwater discharge on temperature. Anyways, if we have reliable estimates that are easy to incorporate, it might be worth adding that to our list of data to pull. 

Some ideas:
- For the NHM fabric, PRMS input attributes (`seg_shade`, `covden_sum`, `covden_win`)?
- For either the NHM/NHDv2 fabric, NLCD-based estimates of percent forest cover in some riparian buffer zone?

**Comment by jds485** [comment]
The inland salinity pipeline has an NLCD 2011 riparian buffer target that could help. I don't think there are SB items for other land cover years, so this would be a static product

**Comment by lekoenig** [comment]
Thanks, Jared, that's exactly what we had in mind - to borrow that target from inland salinity 😉! I'll note here that [StreamCat](https://www.epa.gov/national-aquatic-resource-surveys/streamcat-dataset) also has the following variables that might be of interest for NLCD years 2001, 2006, 2011, and 2016:

```
PctDecid2011CatRp100
PctConif2011CatRp100
PctMxFst2011CatRp100
```

**Comment by lekoenig** [comment]
`CNPY11_BUFF100` is a variable included in the set of attributes compiled by Wieczorek et al. for NHDPlusv2 catchments. The data are downloaded from [this](https://www.sciencebase.gov/catalog/item/570572e2e4b0d4e2b75718bc) ScienceBase repository.  The original data source is the USFS Tree Canopy Cover [dataset](https://www.mrlc.gov/data/nlcd-2011-usfs-tree-canopy-cover-conus) (2011). I've opted to use `CNPY11_BUFF100` as a dataset to represent segment canopy cover/shade because it fits in readily with our existing workflow to download and aggregate various Wieczorek attributes.

However, I'll also add a couple brief notes about the StreamCat attributes listed above, even though we're not currently downloading/processing these data. `CNPY11_BUFF100` is only available for 2011 and therefore represents a single snapshot of riparian canopy cover. In contrast, the StreamCat dataset includes three other NLCD years. The StreamCat variables are taken from NLCD land cover maps as opposed to the USFS tree canopy cover dataset. Here is the description of `PctDecid2011CatRp100` (and `PctDecid2011WsRp100` from the StreamCat data [dictionary](https://gaftp.epa.gov/epadatacommons/ORD/NHDPlusLandscapeAttributes/StreamCat/Documentation/DataDictionary.html):

> % of the local catchment (Cat) and upstream watershed (Ws) classified as deciduous forest land cover within a 100-m wide buffer of the NHD stream lines (Rp100). Derived as the intersection between RipBuf100 and nlcd2011.tif (class 41) landscape layers.

Because StreamCat uses the NLCD data, these attributes are separated by deciduous, coniferous, and mixed forest canopies. I could see an argument for using the StreamCat variables, for example, if water temperature is modulated by riparian cover/shade year-round (conifer forest) versus primary during the growing season (deciduous, mixed forest).
